### ISSUE TITLE
[1.20.1] Create mod Threshold Switch

### ISSUE THREAD

**Issue by TeoH1gh** [Buuz135/FunctionalStorage#229] opened 2023-11-16 12:32 UTC
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:** 1.2.5

**Titanium Version:** 3.8.23

**Crashlog If Applicable (Upload to pastebin/gist):**

When using the threshold switch from the Create mod it reads the drawers as full as soon as you input a stack of items. With the storage drawers mod it can correctly read the fill percentage of a drawer.

**Comment by Matyrobbrt** [comment] 2024-07-16 19:59
Duplicate of #217.

**Closed** 2024-07-16 20:00 UTC
Labels: type: bug, version: 1.20

**Comment by bloodscon** [comment] 2025-05-14 17:29
the create threshold switch does not like the Void upgrade if you have no void upgrade in the drawer I have noticed the switch works fine
